version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday"
    # Assign reviewers
    reviewers:
      - "selezai"
    # Labels on pull requests for version updates
    labels:
      - "npm"
      - "dependencies"
    # Specify version update behavior
    versioning-strategy: increase
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Configure security updates
    security-updates-only: false
    # Configure dependency type updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "selezai"
    labels:
      - "github-actions"
      - "dependencies"
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
      include: "scope"
